### ISSUE TITLE
Fix Null Reference Issue in RecipeToRecipeViewModelConverter

### ISSUE THREAD

**Issue by ctorx** [ctorx/brewgr.com#31]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Brewgr.Web.Mappers.RecipeToRecipeViewModelConverter.Convert(ResolutionContext context)
   at AutoMapper.MappingExpression`2.<>c__DisplayClass23.<ConvertUsing>b__22(ResolutionContext context)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.CustomMapperStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
```

**Comment by KillaBee2k5** [comment]
Are there steps to reproduce this bug?

**Comment by ctorx** [comment]
On closer inspection, it looks like this is happening on the print page, when the print URL is accessed for a recipe that no longer exists (i.e. marked not active or not public).  The page is throwing a 500 when it should be throwing a 404 instead.
